# Generated by Django 3.1.6 on 2021-02-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_newsorganisation_user_sources'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='news_preferences',
            field=models.ManyToManyField(to='news.NewsOrganisation'),
        ),
    ]
