# Generated by Django 3.1.6 on 2021-02-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_newsorganisation_user_sources'),
        ('users', '0002_customuser_news_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='likes',
            field=models.ManyToManyField(to='news.NewsArticle'),
        ),
    ]
