# Generated by Django 3.1.6 on 2021-02-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20210218_1024'),
        ('users', '0003_customuser_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='news_preferences',
        ),
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(related_name='following', to='news.NewsOrganisation'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='news.NewsArticle'),
        ),
    ]
