# Generated by Django 3.1.6 on 2021-02-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20210222_0259'),
        ('users', '0004_auto_20210219_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='saves',
            field=models.ManyToManyField(related_name='saves', to='news.NewsOrganisation'),
        ),
    ]
