# Generated by Django 3.1.6 on 2021-02-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20210222_0259'),
        ('users', '0005_customuser_saves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='saves',
            field=models.ManyToManyField(related_name='saves', to='news.NewsArticle'),
        ),
    ]
