# Generated by Django 3.1.6 on 2021-02-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20210222_0259'),
        ('users', '0006_auto_20210222_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='following',
        ),
        migrations.AddField(
            model_name='customuser',
            name='follow_category',
            field=models.ManyToManyField(related_name='followed_by', to='news.Category'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='follow_news_org',
            field=models.ManyToManyField(related_name='followed_by', to='news.NewsOrganisation'),
        ),
    ]
