# Generated by Django 3.1.6 on 2021-02-07 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_address', models.CharField(max_length=200, unique=True)),
                ('heading', models.CharField(max_length=100)),
                ('snippet', models.TextField()),
                ('published_date', models.DateField()),
                ('author', models.CharField(max_length=30, null=True)),
                ('news_organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newsorganisation')),
            ],
            options={
                'ordering': ['published_date'],
            },
        ),
    ]
