# Generated by Django 3.1.6 on 2021-02-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
