# Generated by Django 3.1.6 on 2021-02-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticle_image_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(default='general', max_length=50, null=True),
        ),
    ]
