# Generated by Django 3.1.6 on 2021-02-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsarticle_category'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['article_address'], name='news_newsar_article_924406_idx'),
        ),
    ]
