# Generated by Django 3.1.6 on 2021-02-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210213_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='published_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
