# Generated by Django 3.1.6 on 2021-02-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210213_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='article_address',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='heading',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image_source',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
