# Generated by Django 3.1.6 on 2021-02-17 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0006_auto_20210213_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsorganisation',
            name='user_sources',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
