# Generated by Django 3.1.6 on 2021-02-18 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_newsorganisation_user_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='news_organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='news.newsorganisation'),
        ),
    ]
