# Generated by Django 3.1.7 on 2021-02-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20210222_0259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={},
        ),
    ]
